/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\Diplomarbeit\Winfact-Geschwindigkeitsregelung\FuzzyV1.fuz from:30.12.2019 14:32:04
  Timestamp    : 30.12.2019 14:34:06

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 2
     e_winkel
     e_v

    Outputs: 2
     u_winkel
     u_v

    Rules: 10

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#ifndef FuzzyV1_F4
#define FuzzyV1_F4 FuzzyV1_F4



#include "fuzzy_F4.h"

#ifdef __cplusplus
  extern "C" {
#endif

void FuzzyV1_F4_SetNumType(void);

void FuzzyV1_F4_init(void);

void FuzzyV1_F4_calc(
       const NumTypeF4_t i0,
       const NumTypeF4_t i1,
       NumTypeF4_t *o0,
       NumTypeF4_t *o1);

void FuzzyV1_F4_free(void);
#ifdef __cplusplus
  }
#endif


#endif
